/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime traffic snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Traffic snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeTrafficResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime forwarding connections snapshot */
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connections snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeConnectionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get runtime diagnostic logs */
        get: {
            parameters: {
                query?: {
                    level?: "all" | "info" | "warn" | "error";
                    q?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeLogsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/proxy/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check HTTP/SOCKS proxy chain connectivity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RuntimeProxyCheckRequest"];
                };
            };
            responses: {
                /** @description Proxy check result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeProxyCheckResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run build config */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RuntimePlanRequest"];
                };
            };
            responses: {
                /** @description Plan result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimePlanResponse"];
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build config and restart sing-box */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RuntimeReloadRequest"];
                };
            };
            responses: {
                /** @description Reload result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeReloadResponse"];
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get forwarding runtime status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forwarding runtime status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingRuntimeStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get forwarding runtime summary and selected nodes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forwarding summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get forwarding node eligibility policy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forwarding policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingPolicyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/policy/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update forwarding node eligibility policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateForwardingPolicyRequest"];
                };
            };
            responses: {
                /** @description Forwarding policy updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingPolicyResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start forwarding runtime */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forwarding started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingRuntimeStatusResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                409: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/forwarding/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop forwarding runtime */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forwarding stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForwardingRuntimeStatusResponse"];
                    };
                };
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get routing bypass settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Routing bypass settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingSettingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/routing/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update routing bypass settings */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRoutingSettingsRequest"];
                };
            };
            responses: {
                /** @description Routing bypass settings updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingSettingsResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                500: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/routing/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get routing and geo summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Routing diagnostics summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingSummaryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Subscription"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Subscription"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubscriptionRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Subscription"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                404: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            responses: {
                /** @description Refresh result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshSubscriptionResponse"];
                    };
                };
                404: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nodes */
        get: {
            parameters: {
                query?: {
                    enabled?: 0 | 1;
                    sub_id?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Node"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test node connectivity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        node_ids: string[];
                        /**
                         * @default http
                         * @enum {string}
                         */
                        mode?: "http" | "ping";
                    };
                };
            };
            responses: {
                /** @description Test result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                node_id?: string;
                                status?: string;
                                latency_ms?: number | null;
                                error?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/forwarding/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch set forwarding enabled for nodes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        node_ids: string[];
                        forwarding_enabled: boolean;
                    };
                };
            };
            responses: {
                /** @description Batch update result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                updated?: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update node */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNodeRequest"];
                };
            };
            responses: {
                /** @description Updated node */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Node"];
                        };
                    };
                };
                404: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: components["schemas"]["ErrorObject"];
        };
        ErrorObject: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Subscription: {
            id: string;
            name: string;
            url: string;
            /** @enum {string} */
            type: "singbox";
            enabled: boolean;
            auto_update_enabled: boolean;
            refresh_interval_sec: number;
            used_bytes?: number | null;
            total_bytes?: number | null;
            remaining_bytes?: number | null;
            usage_percent?: number | null;
            expire_at?: string | null;
            profile_web_page?: string | null;
            profile_update_interval_sec?: number | null;
            created_at: string;
            updated_at: string;
        };
        CreateSubscriptionRequest: {
            name?: string;
            url: string;
            /**
             * @default singbox
             * @enum {string}
             */
            type: "singbox";
            /** @default false */
            auto_update_enabled: boolean;
            /** @default 3600 */
            refresh_interval_sec: number;
        };
        UpdateSubscriptionRequest: {
            id: string;
            name?: string;
            url?: string;
            enabled?: boolean;
            auto_update_enabled?: boolean;
            refresh_interval_sec?: number;
        };
        RefreshSubscriptionResponse: {
            sub_id?: string;
            not_modified?: boolean;
            nodes_total?: number;
            nodes_enabled?: number;
            fetched_at?: string;
        };
        Node: {
            id: string;
            sub_id: string;
            tag: string;
            name: string;
            type: string;
            enabled: boolean;
            forwarding_enabled: boolean;
            server?: string;
            server_port?: number;
            network?: string;
            tls_enabled?: boolean;
            last_test_at?: string | null;
            last_latency_ms?: number | null;
            last_test_status?: string | null;
            last_test_error?: string | null;
            created_at: string;
        };
        UpdateNodeRequest: {
            id: string;
            name?: string;
            enabled?: boolean;
            forwarding_enabled?: boolean;
        };
        RuntimeStatusResponse: {
            data: {
                config_version: number;
                config_hash: string;
                forwarding_running: boolean;
                nodes_included: number;
                last_apply_duration_ms: number;
                last_apply_success_at?: string | null;
                last_reload_at?: string;
                last_reload_error?: string;
                ports: {
                    http?: number;
                    socks?: number;
                };
            };
        };
        RuntimeTrafficResponse: {
            data: {
                sampled_at: string;
                source: string;
                rx_rate_bps: number;
                tx_rate_bps: number;
                rx_total_bytes: number;
                tx_total_bytes: number;
            };
        };
        RuntimeConnectionsResponse: {
            data: {
                active_count: number;
                items: {
                    id: string;
                    node_id: string;
                    node_name: string;
                    node_type: string;
                    target: string;
                    status: string;
                    last_test_at?: string | null;
                    latency_ms?: number | null;
                    error?: string | null;
                    forwarding: boolean;
                    last_updated: string;
                }[];
            };
        };
        RuntimeLogsResponse: {
            data: {
                items: {
                    timestamp: string;
                    level: string;
                    source: string;
                    message: string;
                }[];
            };
        };
        RuntimeProxyCheckRequest: {
            /** @example https://www.gstatic.com/generate_204 */
            target_url?: string;
            /** @default 5000 */
            timeout_ms: number;
        };
        RuntimeProxyCheckResponse: {
            data: {
                target_url: string;
                checked_at: string;
                http: components["schemas"]["RuntimeProxyCheckItem"];
                socks: components["schemas"]["RuntimeProxyCheckItem"];
            };
        };
        RuntimeProxyCheckItem: {
            enabled: boolean;
            proxy_url: string;
            connected: boolean;
            tls_ok: boolean;
            status_code?: number | null;
            latency_ms?: number | null;
            error?: string | null;
            egress_ip?: string | null;
        };
        ForwardingRuntimeStatusResponse: {
            data: {
                running: boolean;
                /** @enum {string} */
                status: "running" | "stopped" | "error";
                error_message?: string | null;
            };
        };
        ForwardingSummaryResponse: {
            data: {
                running: boolean;
                /** @enum {string} */
                status: "running" | "stopped" | "error";
                error_message?: string | null;
                selected_nodes_count: number;
                nodes: {
                    id: string;
                    name: string;
                    tag: string;
                    type: string;
                    last_status?: string | null;
                    last_latency_ms?: number | null;
                }[];
            };
        };
        ForwardingPolicyResponse: {
            data: {
                healthy_only_enabled: boolean;
                max_latency_ms: number;
                allow_untested: boolean;
                node_test_timeout_ms: number;
                node_test_concurrency: number;
                updated_at?: string | null;
            };
        };
        UpdateForwardingPolicyRequest: {
            healthy_only_enabled: boolean;
            max_latency_ms: number;
            allow_untested: boolean;
            node_test_timeout_ms: number;
            node_test_concurrency: number;
        };
        RoutingSettingsResponse: {
            data: {
                bypass_private_enabled: boolean;
                bypass_domains: string[];
                bypass_cidrs: string[];
                updated_at?: string;
            };
        };
        RoutingSummaryResponse: {
            data: {
                bypass_private_enabled: boolean;
                bypass_domains_count: number;
                bypass_cidrs_count: number;
                updated_at?: string;
                notes: string[];
            };
        };
        UpdateRoutingSettingsRequest: {
            bypass_private_enabled: boolean;
            bypass_domains?: string[];
            bypass_cidrs?: string[];
        };
        RuntimePlanRequest: {
            /** @default false */
            include_disabled_nodes: boolean;
        };
        RuntimePlanResponse: {
            data: {
                nodes_included: number;
                tags: string[];
                config_hash: string;
            };
        };
        RuntimeReloadRequest: {
            /** @default true */
            force_restart: boolean;
        };
        RuntimeReloadResponse: {
            data: {
                config_version: number;
                config_hash: string;
                nodes_included: number;
                restart_output?: string;
                reloaded_at: string;
            };
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
